<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'KISSmetrics\\' => array($vendorDir . '/kissmetrics/kissmetrics-php/src'),
);
